In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.layers import IntegerLookup
from tensorflow.keras.layers import Normalization
from tensorflow.keras.layers import StringLookup
model = tf.keras.models.load_model('model_percobaan', compile=False)

In [2]:
def preprocess(filename):
    dataku = pd.read_csv(filename)
    dataku = dataku.drop(["Country","Age_0-9","Age_10-19","Age_20-24","Age_25-59","Age_60+","Gender_Female","Gender_Male","Gender_Transgender","Contact_Dont-Know","Contact_No","Contact_Yes"], axis=1)
    
    def dataframe_to_dataset(dataframe):
        dataframe = dataframe.copy()
        labels = pd.concat([dataframe.pop(x) for x in ['Severity_Mild','Severity_Moderate','Severity_None','Severity_Severe']], axis=1)
        ds = tf.data.Dataset.from_tensor_slices((dict(dataframe), labels))
        ds = ds.shuffle(buffer_size=len(dataframe))
        return ds
    
    ds = dataframe_to_dataset(dataku)
    ds = ds.batch(32)
    return ds
    

In [3]:
def predict(data):
    prediction = model.predict(data)
    return prediction

In [4]:
if __name__ == '__main__':
    ''' for test'''
    test = preprocess('validation_data.csv')
    prediction = predict(test)
    print(prediction)

C:\Users\LABKOM\anaconda3\envs\ijak1\lib\site-packages\keras\engine\functional.py:566: UserWarning: Input dict contained keys ['Unnamed: 0'] which did not match any model input. They will be ignored by the model.
  inputs = self._flatten_to_reference_inputs(inputs)


1980/1980 [==============================] - 3s 1ms/step
[[0.2513039  0.2478699  0.2522352  0.24859104]
 [0.2513039  0.2478699  0.2522352  0.24859104]
 [0.2513039  0.2478699  0.2522352  0.24859104]
 ...
 [0.2513039  0.2478699  0.2522352  0.24859104]
 [0.2513039  0.2478699  0.2522352  0.24859104]
 [0.2513039  0.2478699  0.2522352  0.24859104]]
